# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e2c4455d8b75acca2987b0e21c03dc78e52d677b9b52d7083150331e77763732310fad9c4d4485f09e3929c6f452c8e62793c68bf20d98628edd3c23a3f384c
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

test:
  secret_key_base: e5367c2f6b96ed4790970e3d177a53ab43032cc5c1cc42c54c3966568c940bcabb1c975fbb28a245cb788783daebeccc2b26df22f265442bb3917e79d77a9dcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>